---
# Manifest file downloaded from fusion
externalId: tr-create_ts_asset_mapping
name: create_ts_asset_mapping
query:
    file: transformation.sql
destination:
    type: timeseries
ignoreNullFields: true
shared: true
action: update
schedule:
    interval: 39 * * * *
    isPaused: false
dataSetExternalId: uc:001:oee:ds
authentication:
    clientId: ${COGNITE_CLIENT_ID}
    clientSecret: ${COGNITE_CLIENT_SECRET}
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
    # Optional: If idP requires providing the scopes
    cdfProjectName: ${CDF_PROJECT_NAME}
    scopes:
        - https://westeurope-1.cognitedata.com/.default
